### PR TITLE
Move to use conda to manage R dependencies.

### PR DESCRIPTION
**Pull request by bloodearnest**
This allows us to define depenencies in a yaml file.

### CODE REVIEW

**Review by sebbacon — APPROVED** [review]
Great. As Will has asked elsewhere -- how does one upgrade a package or add a new one?

**Comment by bloodearnest** [comment]
> Great. As Will has asked elsewhere -- how does one upgrade a package or add a new one?

So I generated that original yaml by manually installing stuff unpinned then doing `conda env export > r-environment.yml`.

I'm trying to get towards a pip-compile workflow, where we have a simple top level deps file with pinned versions, and then generate the full env from here. But unlike pip-compile, I think we actually need to create a conda env, install, then capture, as it can't seem to do that just from the dependency resolver (which is very slow). 

My rough plan is to have a Makefile in this repo we can use that will re-use the docker image to create a throwaway env to generate the r-environment.yml from.

**Comment by sebbacon** [comment]
This sounds like a good plan! Perhaps via a second Dockerfile that uses the output of the first as a base image?

**Comment by bloodearnest** [comment]
I managed to mimic the pip-compile workflow fairly closely in the end, and figured out how to do it without installing all the packages.

**Comment by bloodearnest** [comment]
This working, however it has a major flaw: it's using R 3.6.0. 

Tried moving to 4.0 with conda, but there were some packages that did not support 4.0

**Pull request closed without merging**
